<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-30T20:10:19 IST" name="Suite" finished-at="2025-04-30T20:11:02 IST" duration-ms="42257">
    <groups>
      <group name="E2E Testing">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:Learnings.Tests.SubmitOrderTest@2da59753]" name="submitOrder" class="Learnings.Tests.SubmitOrderTest"/>
      </group> <!-- E2E Testing -->
    </groups>
    <test started-at="2025-04-30T20:10:19 IST" name="Error Validations" finished-at="2025-04-30T20:10:36 IST" duration-ms="16991">
      <class name="Learnings.Tests.ErrorValidations">
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.ErrorValidations@6c0d9d86]" started-at="2025-04-30T20:10:19 IST" name="lounchApplication" finished-at="2025-04-30T20:10:24 IST" duration-ms="5068" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method signature="ErrorValidationsTest()[pri:0, instance:Learnings.Tests.ErrorValidations@6c0d9d86]" started-at="2025-04-30T20:10:24 IST" name="ErrorValidationsTest" finished-at="2025-04-30T20:10:25 IST" duration-ms="942" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorValidationsTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.ErrorValidations@6c0d9d86]" started-at="2025-04-30T20:10:25 IST" name="tearDown" finished-at="2025-04-30T20:10:26 IST" duration-ms="130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.ErrorValidations@6c0d9d86]" started-at="2025-04-30T20:10:26 IST" name="lounchApplication" finished-at="2025-04-30T20:10:27 IST" duration-ms="1285" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method retried="true" signature="productValidationCheck()[pri:0, instance:Learnings.Tests.ErrorValidations@6c0d9d86]" started-at="2025-04-30T20:10:27 IST" name="productValidationCheck" finished-at="2025-04-30T20:10:30 IST" duration-ms="3544" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Learnings.Tests.ErrorValidations.productValidationCheck(ErrorValidations.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productValidationCheck -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.ErrorValidations@6c0d9d86]" started-at="2025-04-30T20:10:30 IST" name="tearDown" finished-at="2025-04-30T20:10:30 IST" duration-ms="62" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.ErrorValidations@6c0d9d86]" started-at="2025-04-30T20:10:30 IST" name="lounchApplication" finished-at="2025-04-30T20:10:33 IST" duration-ms="2905" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method signature="productValidationCheck()[pri:0, instance:Learnings.Tests.ErrorValidations@6c0d9d86]" started-at="2025-04-30T20:10:33 IST" name="productValidationCheck" finished-at="2025-04-30T20:10:36 IST" duration-ms="2289" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Learnings.Tests.ErrorValidations.productValidationCheck(ErrorValidations.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productValidationCheck -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.ErrorValidations@6c0d9d86]" started-at="2025-04-30T20:10:36 IST" name="tearDown" finished-at="2025-04-30T20:10:36 IST" duration-ms="87" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Learnings.Tests.ErrorValidations -->
    </test> <!-- Error Validations -->
    <test started-at="2025-04-30T20:10:37 IST" name="Tests" finished-at="2025-04-30T20:11:02 IST" duration-ms="24891">
      <class name="Learnings.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.SubmitOrderTest@2da59753]" started-at="2025-04-30T20:10:37 IST" name="lounchApplication" finished-at="2025-04-30T20:10:39 IST" duration-ms="2341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Learnings.Tests.SubmitOrderTest@2da59753]" started-at="2025-04-30T20:10:39 IST" name="submitOrder" data-provider="getData" finished-at="2025-04-30T20:10:47 IST" duration-ms="7552" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{passWord=!123weSDF, userName=nikhil1997@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.SubmitOrderTest@2da59753]" started-at="2025-04-30T20:10:47 IST" name="tearDown" finished-at="2025-04-30T20:10:47 IST" duration-ms="80" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.SubmitOrderTest@2da59753]" started-at="2025-04-30T20:10:47 IST" name="lounchApplication" finished-at="2025-04-30T20:10:49 IST" duration-ms="2486" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Learnings.Tests.SubmitOrderTest@2da59753]" started-at="2025-04-30T20:10:49 IST" name="submitOrder" data-provider="getData" finished-at="2025-04-30T20:10:57 IST" duration-ms="7764" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{passWord=#345rtFGH, userName=mayur1995@gmail.com, productName=IPHONE 13 PRO}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.SubmitOrderTest@2da59753]" started-at="2025-04-30T20:10:57 IST" name="tearDown" finished-at="2025-04-30T20:10:57 IST" duration-ms="91" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.SubmitOrderTest@2da59753]" started-at="2025-04-30T20:10:57 IST" name="lounchApplication" finished-at="2025-04-30T20:10:59 IST" duration-ms="1408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method signature="MyOrders()[pri:0, instance:Learnings.Tests.SubmitOrderTest@2da59753]" started-at="2025-04-30T20:10:59 IST" name="MyOrders" finished-at="2025-04-30T20:11:01 IST" depends-on-methods="Learnings.Tests.SubmitOrderTest.submitOrder" duration-ms="2255" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Learnings.Tests.SubmitOrderTest.MyOrders(SubmitOrderTest.java:93)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MyOrders -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.SubmitOrderTest@2da59753]" started-at="2025-04-30T20:11:01 IST" name="tearDown" finished-at="2025-04-30T20:11:02 IST" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Learnings.Tests.SubmitOrderTest -->
    </test> <!-- Tests -->
  </suite> <!-- Suite -->
</testng-results>
